// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToExcel(arg1, arg2) {
  return window['go']['main']['App']['ExportToExcel'](arg1, arg2);
}

export function GetOLTs() {
  return window['go']['main']['App']['GetOLTs']();
}

export function GetOltDetails(arg1) {
  return window['go']['main']['App']['GetOltDetails'](arg1);
}

export function GetProcessedGponData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProcessedGponData'](arg1, arg2, arg3);
}

export function GetProcessedOntData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetProcessedOntData'](arg1, arg2, arg3, arg4);
}

export function GetProcessedSpecificOntData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetProcessedSpecificOntData'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}
