// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetOLTs():Promise<Array<model.OLT>>;

export function GetOltDetails(arg1:string):Promise<model.OLT>;

export function GetProcessedGponData(arg1:string,arg2:string,arg3:string):Promise<model.ProcessedGponData>;

export function GetProcessedOntData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.ProcessedOntData>;

export function GetProcessedSpecificOntData(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<model.ProcessedOntData>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;
